### ISSUE TITLE
MTBLS263 description

### ISSUE THREAD

**Issue by sneumann** [HUPO-PSI/mzTab#47] opened 2017-11-09 13:15 UTC
Hi, as part of the mzTab-M discussions we are using 
https://www.ebi.ac.uk/metabolights/MTBLS263 as an example. 
There are some aspects unclear to me:
1) Description says samples came from 30 donors, but `Source` only has one value -> Just one person ? Everything pooled in one vial ?
2) There are 4 `Preparation replicate`s
3) From the preparation `1` three injections were performed. 

From my understanding of the ISA-Tab approach, there should be only four rows in the sample table, with four distinct sample names, and then six rows in the a_assay.txt, where three rows would have the same sample name but three different `MS Assay Names`. 

Yours, Steffen

**Comment by proccaserra** [comment] 2017-11-09 14:22
@sneumann the initial description is misleading as it covers a study which includes samples from the volunteer used in that instance (as far as I can tell). " The same blood sample preparation was injected 3x into the LC-MS at 80-min intervals. We thus obtained within-sample CVs (designated as CVwi), which were less than 0.1 in 107 of 126 compounds (85%). Only 10 compounds showed CVwi of 0.1-0.2, while 9 had CVwi >0.2. Second, we also examined sample-to-sample variation caused by sample preparation. Three samples were independently prepared from the same blood sample (one person)"

Your conclusions about how this should be represented in ISA are correct. The ISA s_study file would need to be fixed by the repository.

The description of the experiment lacks a bit of precision when it comes to the sample preparation, ie whether there were 3 or 4 aliquots derived from the initial sample. The current representation means the latter.

Finally, another potentially difficulty is the consistence declaration and use of study variable / study factors in mztab and isa.

**Comment by andrewrobertjones** [comment] 2018-04-19 14:44
Closed, since this relates to an ISATAB issue

**Closed by andrewrobertjones** 2018-04-19 14:44 UTC
